export const data =[{
    ids: "0",
    content: "The recipe generation app is a marvel that is created using the Django framework, it is an application where users are able to upload an image containing the images which they possess, there will then be an object recognition model which will detect the ingredients in the image and compile them into a list which the user can add or delete, the list of ingredients will then be passed through an LLM which will in turn give a recipe. Users will be able to save the recipe or go back to the image gallery page. This application implements a simple user account system which allows for there to be multiple user accounts each with their own saved recipe list. Any recipe created by any user will also be stored and displayed in a global recipes page, where users can view recipes which have been created by other users, whether the recipe is saved or unsaved."
},
{
    ids: "1",
    content: "The survey question creator is a software that allows for users to create 3 different types of survey questions, short answer, essay, and multiple choice questions. This web application was built using the Django framework, and is designed and created with the intention of being integrated into a much larger web application, to be specific, a Google Surveys clone. This project was done by a team with the use of the SCRUM framework, with communication and collaboration with other teams whose job was the development of the other parts of the overarching project, such as user account management systems, survey logic, and even scheduling systems. This software is an integral part towards the project as a whole, as it is what is responsible for actually creating, editing, and storing the survey questions."
},
{
    ids: "2",
    content : "The AI Chatbot which we have created combines a variety of features to create an innovative chatbot that is meant to be able to be spoken to and speak back as well. The implementation of such a chatbot requiring a variety of solutions, the chatbot can be divided into 3 main components, the speech to text component, the LLM component, and the text to speech component, these 3 components when combined together creates a chatbot that is able to be spoken to and can even speak back as well. The speech to text component comprises of a class with 2 functions, one to record audio and one to transcribe the recorded audio into text, this has been done through th euse of several Python libraries such as pyaudio and speech_recognition. The LLM component makes use of a quantized model that is based on the Llamma-2-7b model, the model is hosted locally on the machine using something called LM studio. The text to speech component uses the gTTS library to transform the output text of the LLM into an actual voice. Combined together, all of these components give rise to an innovative Chatbot that is able to be spoken to, and can speak by itself as well "
},
{
    ids: "3",
    content : "The iD8 Club, which is the dedicated IT club of James Cook University Singapore, the website me and my president has created is meant as an easy way for anyone who wishes to know more about he iD8 club to obtain more information regarding it. The website is currently hosted using AWS Lightsail and is using the WordPress content management system. "
},
{
    ids: "4",
    content : "During the course of my university years, I had created several android applications as part of a project. a calculator app and a memory game. The calculator app was programmed using Java and has the basic functionality of a calculator, able to calculate floating points. This calculator also has the added functionality of having sounds for each button as well as background music for the calculator as well. The memory game was programmed using Kotlin, a game where a there is a 3 * 4 grid of pictures where users will have to match the pictures within the grid, there is a high score system which will keep track of the high score of the user which will be kept track and stored even if the user turns the application off the high score will still be stored, this is done through the implementation of an SQLITE database. This application also implemented sounds effects and background music as well."
},
{
    ids: "5",
    content : "During the course of my university years, I have also created several Python and Java projects, these projects included programs such as book trackers which utilized the Kivi library to create a GUI using only Python, implementing proper programming practices. For Java, I have done several projects, the biggest of them being a project where we had to create a rainfall analyzer, where the user will be able to upload a csv with rainfall data, and the program will then display a graph of the data with various features such as tooltips. These projects have instilled in me good coding practice and have been integral with giving me the necessary foundations for my software development career."
},
{
    ids: "6",
    content : "I have also worked on a 3D Modelling project where I had to create 3D Models and environments using th Autodesk Maya software. I creeated a variety of models and also modified some models which I had downloaded online as well, the models which I created included things such as trees, chairs, tables, artillery canons, trenches and more. All of to most of the models which I have created were either textured using basic texturing or using UV-texturing. I had also used the models which I have created to create an animation utilizing them, this animation makes use of the various I have created to display a short aniamtion about war. The animation used skeleton aniamtion and key-frame aniamtion as well, both were integral for th ecompletion of my animation."
}];